name: Deploy to Firebase Hosting on dev merge
'on':
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          envkey_AIRTABLE_BASE_ID: ${{ secrets.DEV_AIRTABLE_BASE_ID }}
          envkey_AIRTABLE_TABLE_NAME: ${{ secrets.DEV_AIRTABLE_TABLE_NAME }}
          file_name: .env
          fail_on_empty: false
      - run: npm ci && npm run build
      - uses: www-norma-dev/firebase-hosting-functions-deploy@main
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LYBERTYX }}
          projectID: herit-dev
          channelId: live
